/**
 * Card To Account AssociationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RQCardToAccountAssociation {
  accountId: string;
}

export const rQCardToAccountAssociationSchema: Schema<RQCardToAccountAssociation> = object(
  { accountId: ['accountId', string()] }
);
